airflow:
  extraPipPackages:
  - apache-airflow-providers-cncf-kubernetes

dags:
  gitSync:
    branch: main
    containerName: git-sync
    enabled: true
    env: []
    envFrom: null
    extraVolumeMounts: []
    maxFailures: 0
    period: 5s
    repo: https://github.com/adilkhan49/airflow-test.git
    resources: {}
    securityContext: {}
    securityContexts:
      container: {}
    subPath: dags
    uid: 65533
    wait: null
  mountPath: null
  persistence:
    accessMode: ReadWriteOnce
    annotations: {}
    enabled: false
    existingClaim: null
    size: 1Gi
    storageClassName: null
    subPath: null